version: '3.1'
services:

  devops-achat:
    container_name: tpachat
    image: "tpachat"
    build: .
    networks:
      - test_default   
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devops-achat-mysql:3306/achatdb?useSSL=false
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    
    depends_on:
      - mysqldb
   
  mysqldb:
    container_name: achat-mysql_2
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - /home/vagrant/nexus/nexus-data:/sonatype-work       
    networks:
      - mynetwork   

   

volumes:
  /home/vagrant/nexus/nexus-data:/sonatype-work:
networks:
  mynetwork:
